[alias]
t = "nextest run"
r = ["watch", "-c", "--ignore", "src/http/static/*", "-x", "run --profile dev-fast"]
rr = ["watch", "-c", "-x", "run --release"]
c = ["watch", "-c", "-x", "clippy --all-targets"]
